### ISSUE TITLE
How to catch parsing errors

### ISSUE THREAD

**Issue by ishandutta2007** [rexxars/eventsource-parser#10]
How do I catch in such scenarios:
`str` is rightly printed but when it enters `parser.feed`, it gets stuck and never returns; nor does it throw any errors.
And hence it never reaches `console.log("event", event)` even

```
import { createParser } from 'eventsource-parser'
  const parser = createParser((event) => {
    console.log("event", event)
    if (event.type === 'event') {
      onMessage(event.data)
    }
  })
  for await (const chunk of streamAsyncIterable(resp.body!)) {
    const str = new TextDecoder().decode(chunk)
    console.log("str", str)
    parser.feed(str)
  }
```

`resp` is the respose object and `onMessage` is just a function

**Comment by ishandutta2007** [comment]
On debugging I found it encounters the `break` on this [line](https://github.com/rexxars/eventsource-parser/blob/08ad1f7873931c36c9dda912e90558eb04c8295c/src/parse.ts#L95) and since it breaks out of while loop it never processes `parseEventStreamLine`. 
What I understand `event` was supposed to be returned by `feed` but since it reaches the end of the function the callback passed to `createParser` never gets called.

**Comment by rexxars** [comment]
Could you provide some example data?

**Comment by ishandutta2007** [comment]
@rexxars As I said my data isn't valid format starting with `data:` .
It's some json, like somthing like this `{key1:data1,key2:data2}` but not what this library parses out of the box.
I didn't expect the API server to return it , which is why I had to suffer code freeze on production. 
Now I handle it like this but Ideally `eventsource-parser` library should have through some error while parsing
```
    if (str.includes('some_keyword')) {
      console.log("non parsable str")
      onMessage(str)
    } else {
      parser.feed(str)
    }
```

**Comment by rexxars** [comment]
I don't see you mentioning anything about invalid data, but fair enough - thanks for clarifying.

**Comment by ishandutta2007** [comment]
I guess I meant it by explaining the debugging steps especially `break`-ing etc that it was not a format which `eventsource-parser` expects. Sorry for not being explicit which cased miscommunication. 

Anyways lets keep it as a priority issue for next release. Throwing all invalid cases as exception in loud and clear manner is a must have for any library in today's world where projects depend on hundreds of libraries. I keep hunting for hours which library is making it go in infinite loop .

By the way this is a very nice lib, it eased my parsing headache, we should always thank people of `npm` community for their free contribution before any communication❤️

**Comment by Peek-A-Booo** [comment]
> Could you provide some example data?

This is my code, `console.log(event)` will not run when I receive a value in this format which not starting with `data:`
```typescript
const textDecoder = new TextDecoder()
  let eventSourceParser: EventSourceParser

  return new TransformStream({
    async start(controller) {
      eventSourceParser = createParser(
        (event: ParsedEvent | ReconnectInterval) => {
          console.log(event)
        },
      )
    },
    transform(chunk) {
      const value = textDecoder.decode(chunk)

      // the value is a string like:
      // {
      //   "error": {
      //     "message": "An assistant message with 'tool_calls' must be followed by tool messages responding to each 'tool_call_id'. The following tool_call_ids did not have response messages: call_FwpczVWzU3oIb0t 啊首付款就好
      // SLiCHOt2z",
      //     "type": "invalid_request_error",
      //     "param": "messages",
      //     "code": null
      //   }
      // }
      eventSourceParser.feed(value)
    },
  })
```

**Comment by rexxars** [comment]
Just release [v3.0.0](https://github.com/rexxars/eventsource-parser/releases/tag/v3.0.0) with support for `onError` callback.
