### ISSUE TITLE
preserve \n

### ISSUE THREAD

**Issue by priesty** [rexxars/eventsource-parser#11]
in the streaming output, all the \n was filtered. how can i preserve it

![11](https://github.com/user-attachments/assets/0a678865-c028-4f79-8647-599309a69090)
in this case, If there are more than two ‘\n’ in the chunks data, like this:  'data: event\n\n\n\n', the output should be: data: 'event\n\n'

![image](https://github.com/user-attachments/assets/7c428e35-8b05-4bb3-b7d2-a28c1114b0aa)
![image](https://github.com/user-attachments/assets/928d9d02-7062-441d-9060-47064a75b774)
i found the 2nd '\n' was passed 

pls help

**Comment by rexxars** [comment]
Hi! This is actually in line with the [EventSource specification](https://html.spec.whatwg.org/multipage/server-sent-events.html#parsing-an-event-stream), and also how browsers interpret this.

To preserve newlines, you have to break them into separate `data: ` chunks. In your example, `data: event\n\n\n\n` needs to be encoded as the following:
```
data: event
data: 
data: 


```

As a javascript string, that would be:
```ts
"data: event\ndata: \ndata: \n\n"
```

Note that the last two newlines is to complete the message - the empty data lines are to indicate newlines.

Here's a function that encodes strings like this:
```js
function encodeTextData(text) {
  const data = `${text}`.replace(/(\r\n|\r|\n)/g, '\n')
  const lines = data.split(/\n/)
  let line

  let output = ''
  for (let i = 0, l = lines.length; i < l; ++i) {
    line = lines[i]

    output += 'data: ' + line
    output += i + 1 === l ? '\n\n' : '\n'
  }

  return output
}

console.log(encodeTextData('event\n\n')) // "data: event\ndata: \ndata: \n\n"
```

**Comment by priesty** [comment]
ok, thank you very much!
