### ISSUE TITLE
The stream.ts/ stream.js file should be at root level

### ISSUE THREAD

**Issue by sky-ether-public** [rexxars/eventsource-parser#12]
Hi Developers,
The structure of code for this library is very different from classical npm libraries.
When I was mocking this library using jest I encounter issue while mocking this library.
`Cannot find module 'eventsource-parser/stream'`
The suggestion would be create a index.ts file for routing to stream component.

**Comment by rexxars** [comment]
Hi. It's a shame that jest doesn't support [package exports](https://nodejs.org/api/packages.html#exports).
I've released a new version of the parser that adds legacy exports through root-level files.
You'll find it as [v2.0.0](https://github.com/rexxars/eventsource-parser/releases/tag/v2.0.0) - I dropped support for Node versions older than Node 18.
