### ISSUE TITLE
Thoughts on splitting out the parser

### ISSUE THREAD

**Issue by gschier** [rexxars/eventsource-parser#14]
Hey there, this repo looks great! However, I'm looking to use just the parser, without any of the client logic but it's not made public in this crate.

I'm wondering if you'd either consider splitting the parser into a separate package, or making it public in this crate for external use?

Thanks

**Comment by rexxars** [comment]
Are you mixing this repo with something else? This _is_ just the parser, and this is a TypeScript/Javascript package, not rust.

**Comment by gschier** [comment]
Haha, yes, definitely the wrong repo! I did give this a try but found it to be quite slow for parsing, so found a Rust alternative
