### ISSUE TITLE
Parser.feed(chunk) not trigger onParse callback

### ISSUE THREAD

**Issue by vitjaz** [rexxars/eventsource-parser#16]
Hi! According to the requirements I need to use package version 0.0.5.
Here is my code:

```ts
// this callback not called
const onParse = (event: ParseEvent) => {
    console.log('event in createParser', event)
    if (event.type === 'event') {
      console.log('on parser event message!', event)
      onMessage(event.data)
    } else if (event.type === 'reconnect-interval') {
      console.log('We should set reconnect interval to %d milliseconds', event.value)
    }
  }

  const parser = createParser(onParse)
  
  for await (const chunk of streamAsyncIterable(resp.body!)) {
    const str = new TextDecoder().decode(chunk)   // this is actually string
    console.log('before feed', str)     // we see this log (logging is presented below)
    parser.feed(str)   
  }
```

```
before feed {"text": ["\u0422\u044b \u0432\u0435\u0436\u043b\u0438\u0432\u044b\u0439 \u0430\u0441\u0441\u0438\u0441\u0442\u0435\u043d\u0442 \u043f\u0440\u043e\u0433\u0440\u0430\u043c\u043c\u0438\u0441\u0442\u0430.\n\n### Instruction:\n\u041f\u0440\u043e\u043a\u043e\u043c\u043c\u0435\u043d\u0442\u0438\u0440\u0443\u0439 \u044d\u0442\u043e:\nimport * as esbuild from \"esbuild\"; import fs from \"fs\"; import path from \"node:path\"; import colors from \"picocolors\"; import cssModulesPlugin from \"esbuild-css-modules-plugin\";\n\n### Response:\n\u041a\u043e"]}
```

There are no errors in the console.

**Comment by rexxars** [comment]
What do you mean by this?
> According to the requirements I need to use package version 0.0.5.

Do you need to support Node.js versions lower than v14?

Regardless; this is expected, as this is not a valid SSE message:

> Ты вежливый ассистент программиста.
>
>### Instruction:
>Прокомментируй это:
>import * as esbuild from "esbuild"; import fs from "fs"; import path from "node:path"; import colors from "picocolors"; >import cssModulesPlugin from "esbuild-css-modules-plugin";
>
>### Response:
>Ко

I unfortunately do not have time to provide support for non-current versions of this module - v3 has a new parsing implementation, and also has an `onError` callback that should be helpful.
