### ISSUE TITLE
createParser error from package "compilation"

### ISSUE THREAD

**Issue by 0xGeegZ** [rexxars/eventsource-parser#2]
Hi @Rexxars,

I'm trying to use your library in a Next.js project, but I encounter an error when creating the parser:

```

error - node_modules/eventsource-parser/dist/index.cjs.mjs (3:7) @ <unknown>
error - Cannot read properties of undefined (reading 'createParser')
null

./node_modules/eventsource-parser/dist/index.cjs.mjs
Attempted import error: './index.js' does not contain a default export (imported as 'cjs').

```

Upon inspecting the package, I noticed that index.cjs.mjs tries to import cjs from index.js, but index.js does not export cjs and do not have default export.

Do you have any idea what might be causing this issue? I'm using Next.js 13 with the appDirectory configuration, in case that helps.

Thank you for your assistance.

**Comment by rexxars** [comment]
Hi Guillaume!

Could you try the latest version (1.0.0)? I did some changes to the exports and build tooling

**Comment by 0xGeegZ** [comment]
It work's perfectly :) 

Thanks a lot.
