### ISSUE TITLE
A TransformStream for parsing events

### ISSUE THREAD

**Issue by jollytoad** [rexxars/eventsource-parser#4]
Thanks for this useful library, I've been using it in Deno (via [esm.sh](https://esm.sh/eventsource-parser)) to ingest OpenAI chat streams.
I found it easier to use if wrapped in a [TransformStream](https://developer.mozilla.org/en-US/docs/Web/API/TransformStream), which I thought I'd share, feel free to incorporate it in the library if you feel it's appropriate...

```ts
import {
  createParser,
  type EventSourceParser,
  type ParsedEvent,
} from "eventsource-parser";

/**
 * A TransformStream that ingests a stream of strings and produces a stream of ParsedEvents.
 * 
 * @example
 * const eventStream =
 *   response.body
 *     .pipeThrough(new TextDecoderStream())
 *     .pipeThrough(new EventSourceParserStream());
 */
export class EventSourceParserStream
  extends TransformStream<string, ParsedEvent> {
  constructor() {
    let parser!: EventSourceParser;

    super({
      start(controller) {
        parser = createParser((event) => {
          if (event.type === "event") {
            controller.enqueue(event);
          }
        });
      },
      transform(chunk) {
        parser.feed(chunk);
      },
    });
  }
}
```

**Comment by rexxars** [comment]
Thanks! I've added it to the [v1.1.0](https://github.com/rexxars/eventsource-parser/releases/tag/v1.1.0) release - much appreciated :)

**Comment by jollytoad** [comment]
Ah nice, you are very welcome.

**Comment by sinedied** [comment]
@rexxars not sure why, but
`import {EventSourceParserStream} from 'eventsource-parser/stream'`

Gives me an error:
<img width="1127" alt="image" src="https://github.com/rexxars/eventsource-parser/assets/593151/117f12cc-4220-44cf-8aea-eb56e9a783aa">

I updated to latest 1.1.1 version, and I see the stream file in the node module, so I'm not sure why it fails. Any idea?

**Comment by jollytoad** [comment]
FWIW, seems to import fine in Deno from esm.sh (haven't tried an `npm:` import)... `import { EventSourceParserStream } from "https://esm.sh/eventsource-parser@1.1.1/stream"`

**Comment by rexxars** [comment]
> Is there any chance you could export the `EventSourceParserStream` class from the main package? TS is a bit messed up at the moment for frontend apps...

I'm hesitant to do so because it depends on `TransformStream`, which is not supported in all environments/browsers. Even if not used, having the `class X extends TransformStream` in your bundle will crash in those environments.

Have you tried using `bundler` as the module resolution setting?
